package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Tw61605d'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("Tw61605d")
    name = "TW-61605d"
    description = "View DSL action changes settings on disk (stores inherited build steps as overridden) when step editing is disabled"

    steps {
        script {
            name = "StepAaaaaaaaa"
            scriptContent = "echo testAAAAAA"
        }
        step {
            name = "Dynamic Library Build6"
            type = "PowerShell"
            enabled = false
            executionMode = BuildStep.ExecutionMode.DEFAULT
            param("script.content", "")
        }
        script {
            name = "Step1"
            scriptContent = "echo test"
        }
        script {
            name = "StepZ"
            scriptContent = "echo Z"
        }
        script {
            name = "Step111111xxxxxxx"
            scriptContent = "echo xxxxxxxxxxxxxxxxxxxxxxx"
        }
        script {
            name = "StepYYYY"
            scriptContent = "echo YYYYY"
        }
        powerShell {
            scriptMode = script {
                content = "sleep 60"
            }
        }
    }
}))

